#!/bin/bash

# Instagram- @basudevrout2001
#Background

for fgbg in 48 ; do #Background
    for color in {0..255} ; do # Colors
        # Display the color
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
        
        if [ $((($color + 1) % 7)) == 4 ] ; then
            echo 
        fi
    done
    echo 
done 


exit 0
